### ISSUE TITLE
Exciting App

### ISSUE THREAD

**Issue by RogueMaster** [carvilsi/flipper0-wifi-map#1]
Is this app working? I would like to include it in my firmware (why I ask).

**Comment by carvilsi** [comment]
Hi!
It's already working in a **work in progress** status.

Right now it displays at flipper side and stores at the SDcard, the AP names (anonymized, just to maintain privacy) and aprox distance in meters to the AP and the authentication mode code and time. For the APs that you are reaching while you walk around.

To include it to your flipper, please follow the README, and notice as is mentioned there, you'll need a `ESP32` as companion device with this code [esp32-wifi-map](https://github.com/carvilsi/esp32-wifi-map) and connected to the flipper as is described at the README.
**NOTE:** As you know you'll need to add this flipper code/repo at `applications_user/` folder under `flipperzero-firmware`.

I would like to "draw something like a map" (with AP names and aprox position around Flipper+ESP32), instead to display the data at Flipper side and add some post-processing script for the saved file.
